// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview Flow for improving user-provided prompts using GenAI.
 *
 * This file defines a Genkit flow that takes a user's prompt as input and uses
 * the Gemini API to suggest an improved version of the prompt. This helps users
 * learn how to phrase their prompts more effectively for better AI responses.
 *
 * @Exported Members:
 *   - `improvePrompt`: The main function to call to improve a prompt.
 *   - `ImprovePromptInput`: The TypeScript type for the input to the flow.
 *   - `ImprovePromptOutput`: The TypeScript type for the output of the flow.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

/**
 * Input schema for the improvePrompt flow.
 */
const ImprovePromptInputSchema = z.object({
  originalPrompt: z
    .string()
    .describe('The original prompt provided by the user.'),
});

/**
 * TypeScript type for the input to the improvePrompt flow.
 */
export type ImprovePromptInput = z.infer<typeof ImprovePromptInputSchema>;

/**
 * Output schema for the improvePrompt flow.
 */
const ImprovePromptOutputSchema = z.object({
  improvedPrompt: z
    .string()
    .describe('The AI-suggested improved version of the prompt.'),
});

/**
 * TypeScript type for the output of the improvePrompt flow.
 */
export type ImprovePromptOutput = z.infer<typeof ImprovePromptOutputSchema>;

/**
 * Improves a user-provided prompt using GenAI.
 *
 * @param input - The input containing the original prompt.
 * @returns A promise resolving to the improved prompt.
 */
export async function improvePrompt(input: ImprovePromptInput): Promise<ImprovePromptOutput> {
  return improvePromptFlow(input);
}

/**
 * Defines the prompt for improving the user prompt.
 */
const improvePromptPrompt = ai.definePrompt({
  name: 'improvePromptPrompt',
  input: {schema: ImprovePromptInputSchema},
  output: {schema: ImprovePromptOutputSchema},
  prompt: `You are an AI prompt improver. The user will provide a prompt, and you will re-write the prompt to be the best possible prompt it can be. Return ONLY the re-written prompt.

Original prompt: {{{originalPrompt}}}`,
});

/**
 * Defines the Genkit flow for improving the user prompt.
 */
const improvePromptFlow = ai.defineFlow(
  {
    name: 'improvePromptFlow',
    inputSchema: ImprovePromptInputSchema,
    outputSchema: ImprovePromptOutputSchema,
  },
  async input => {
    const {output} = await improvePromptPrompt(input);
    return output!;
  }
);
